apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demoappjavaweb
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: demoappjavaweb
    spec:
      containers:
      - name: demoappjavaweb
        image: pleungcon.azurecr.io/pleungms/demoappjavaweb:$BUILD_ID
        ports:
        - containerPort: 4567
---
apiVersion: v1
kind: Service
metadata:
  name: demoappjavaweb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: demoappjavaweb